site_name: Edu-Wiki
site_description: 高中知识维基百科
site_author: Edu-Wiki Team
site_url: https://edu-wiki.pages.dev/
repo_name: Nick-zheng-official/edu-wiki
repo_url: https://github.com/Nick-zheng-official/edu-wiki
edit_uri: blob/master/docs/docs/
copyright: Copyright &copy; 2025 Edu-Wiki Team
use_directory_urls: true

docs_dir: docs

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  favicon: static/img/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - 语文:
      - 语文简介: chinese/introduction.md
  - 数学:
      - 数学简介: math/introduction.md
      - 初高衔接:
          - 初高衔接: math/high-school-transition/high-school-transition.md
      - 集合与逻辑用语:
          - 集合与逻辑用语: math/sets-and-logic/sets-and-logic.md
      - 不等式:
          - 不等式: math/inequalities/inequalities.md
      - 函数:
          - 函数: math/functions/functions.md
      - 三角函数:
          - 三角函数: math/trigonometric-functions/trigonometric-functions.md
      - 平面向量:
          - 平面向量: math/plane-vectors/plane-vectors.md
      - 立体几何:
          - 立体几何: math/solid-geometry/solid-geometry.md
      - 圆锥曲线:
          - 椭圆: math/conic-sections/ellipse.md
      - 数列:
          - 数列: math/sequences/sequences.md
      - 导数:
          - 导数: math/calculus/derivative.md
      - 概率统计:
          - 概率统计: math/probability-and-statistics/probability-and-statistics.md
      - 数学技巧: math/math-tricks.md
  - 英语:
      - 英语简介: english/introduction.md
  - 物理:
      - 物理简介: physics/introduction.md
      - 运动学:
          - 冲量与动量: physics/kinematics/impulse-and-momentum.md
          - 简谐运动: physics/kinematics/simple-harmonic-motion.md
          - 圆周运动: physics/kinematics/circular-motion.md
          - 运动学: physics/kinematics/kinematics.md
      - 磁学:
          - 电磁感应: physics/magnetism/electromagnetic-induction.md
      - 交流电:
          - 交流电: physics/alternating-current/alternating-current.md
      - 电学:
          - 电学: physics/electricity/electricity.md
      - 机械波:
          - 机械波: physics/mechanical-waves/mechanical-waves.md
      - 原子物理:
          - 原子物理: physics/atomic-physics/atomic-physics.md
      - 热力学:
          - 热力学: physics/thermodynamics/thermodynamics.md
      - 光学:
          - 光学: physics/optics/optics.md
      - 天体物理:
          - 天体物理: physics/astrophysics/astrophysics.md
  - 化学:
      - 化学简介: chemistry/introduction.md
      - 化学反应原理:
          - 化学反应速率: chemistry/chemical-reaction-principles/chemical-reaction-rate.md
      - 元素化合物:
          - 元素化合物: chemistry/elemental-compounds/elemental-compounds.md
      - 化学反应与能量:
          - 化学反应与能量: chemistry/chemical-reactions-and-energy/chemical-reactions-and-energy.md
      - 氧化还原:
          - 氧化还原: chemistry/redox-reactions/redox-reactions.md
      - 物质分类及转化:
          - 物质分类及转化: chemistry/substance-classification-and-transformation/substance-classification-and-transformation.md
      - 物质的量:
          - 物质的量: chemistry/amount-of-substance/amount-of-substance.md
      - 离子反应:
          - 离子反应: chemistry/ionic-reactions/ionic-reactions.md
      - 有机化学:
          - 有机化学: chemistry/organic-chemistry/organic-chemistry.md
      - 化学知识积累: chemistry/chemistry-knowledge-accumulation.md
  - 生物:
      - 生物简介: biology/introduction.md
      - 生物与环境:
          - 生态系统: biology/environment/ecosystem.md
      - 显微镜:
          - 显微镜: biology/microscope/microscope.md
      - 有机物:
          - 有机物: biology/organic-compounds/organic-compounds.md
      - 物质运输:
          - 物质运输: biology/substance-transport/substance-transport.md
      - 稳态与调节:
          - 神经调节: biology/homeostasis-and-regulation/neural-regulation.md
          - 稳态: biology/homeostasis-and-regulation/homeostasis.md
      - 细胞:
          - 细胞: biology/cells/cells.md
          - 走进细胞: biology/cells/introduction-to-cells.md
      - 细胞代谢:
          - 细胞代谢: biology/cellular-metabolism/cellular-metabolism.md
      - 发酵工程:
          - 发酵工程: biology/fermentation-engineering/fermentation-engineering.md
      - 基因工程:
          - 基因工程: biology/genetic-engineering/genetic-engineering.md
      - 细胞工程:
          - 细胞工程: biology/cell-engineering/cell-engineering.md
      - 生物知识积累: biology/biology-knowledge-accumulation.md

markdown_extensions:
  # 基础扩展
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - abbr

  # 数学公式扩展
  - pymdownx.arithmatex

  # PyMdown Extensions
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ""
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ""
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  copyright: 本作品采用 知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 (CC BY-NC-SA 4.0) 进行许可

extra_javascript:
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - static/js/extra.js
  - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - static/css/extra.css
